name: SonomaSold
favicon: null
layout_spectrum: 0.059487194987013936
typography_spectrum: 0.9057326090987772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#151419'
    - '#9a632b'
    - '#5b2000'
    - '#c18a63'
  brandStrength: 0.375
  lightness: 0.720745220547542
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
