name: SonomaSold
favicon: null
layout_spectrum: 0.059487194987013936
typography_spectrum: 0.9057326090987772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.720745220547542
  saturation: 0.08931511896662414
  rhythmicContrast: 0.15698177134618163
purpose: []
